const leagueNote = {
  week: "0",
  year: "2026",
  text: `<p><font size="3"><b style="">The Wix site is dead.&nbsp;</b>RIP tightmanbuns.com.</font></p><p><font size="3"><br></font></p>
<p><font size="3">After years of tolerating a website that was built during the Obama administration, Slingshot Engaged now has a home worthy of its history.&nbsp;</font></p><p><font size="3"><br></font></p><p><font size="3">With the dawn of vibe coding upon us, I was able to create this new site through ceaseless attention to detail and passion for minutiae.&nbsp;</font></p><p><font size="3"><br></font></p>
<p><font size="3">Here's what you'll find on the new site.</font></p><p><font size="3">__________</font></p>
<p><font size="3"><strong>The Annals</strong> is the full statistical record of this league — career records, single-game records, prestige rankings, head-to-head history, boom/bust rates, playoff odds, the Intercontinental Championship lineage, and more. I think you'll find The Annals far superior to the old site's screenshots of Excel tables.&nbsp;</font></p><p><font size="3">__________</font></p>
<p><font size="3"><strong>Beefcakes</strong> is the owner directory — 14 profile pages, one per manager, with career stats, trophy cases, head-to-head breakdowns, and performance charts going back to 2014.</font></p><p><font size="3">__________</font></p>
<p><font size="3"><strong>The Scouting Report</strong> is the wildcard nestled in the Beefcake profiles. Pull up any owner's profile and hit the button — an AI reads their full statistical history and delivers a scouting report on their playstyle, tendencies, and weaknesses in the unique style of author and cultural critic Chuck Klosterman. Choose from an Analytical, Eulogy, or Ruthless approach to Chuck's style. Some of them are uncomfortably accurate.</font></p><p><font size="3">__________</font></p>
<p><font size="3"><strong>Owner Comparison</strong>, also within the Beefcake profiles, lets you put any two managers side by side — stats, charts, H2H record — in a full overlay. Great for settling arguments.</font></p><p><font size="3">__________</font></p>
<p><font size="3"><strong>League Weekend Memories</strong> is a community board where anyone can post a memory from a league weekend. Post something. Shout-out to Daniel for this idea.</font></p><p><font size="3">__________</font></p>
<p><font size="3"><strong>Game of Names</strong> is on the homepage just above this league note and it does exactly what it sounds like. Two of the 522 all-time Slingshot team names show up. You pick the one you like the most. Every&nbsp;vote shapes the all-time rankings. It's stupid and you will spend more time on it than you expect.</font></p><p><font size="3">__________</font></p>
<p><font size="3"><strong>Side Hustles</strong>&nbsp;buttons are located above and will be the first thing you see on the new site during the season. They will be updated before kickoff.&nbsp;</font></p><p><font size="3">__________</font></p>
<p><font size="3">The <strong>League Note</strong> will live here during the season. Every week, the note goes up. Bookmark this page.</font></p><p><font size="3">__________</font></p>
<p><font size="3">I spent a lot of time on this over the last couple months. It was wild to see what technology can do and honestly pretty fun to feel in my flow state - when you're doing something you enjoy and you lose track of time - for the first time in a while. I hope you enjoy it.&nbsp; Let me know if you see any issues or bugs or if you have any other ideas to improve the site. From what I learned, these LLMs will never say no to a web design idea...if you can imagine it, it can build it.</font></p>
<p><font size="3">— Jack</font></p>`
};
